# Generated by Django 3.2.8 on 2023-09-11 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20230910_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='residence_ward',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
