# Generated by Django 3.2.8 on 2023-08-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20230831_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
