# Generated by Django 3.2.8 on 2023-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_delete_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('CEO', 'CEO'), ('HOD', 'HOD'), ('EMPLOYEE', 'EMPLOYEE')], default='EMPLOYEE', max_length=20, verbose_name='position'),
        ),
    ]
