# Generated by Django 3.2.8 on 2023-09-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_auto_20230911_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='residence_district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='residence_region',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
