# Generated by Django 3.2.8 on 2023-09-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_user_type_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type_user',
            new_name='type',
        ),
    ]
