# Generated by Django 3.2.8 on 2023-09-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('complaints', '0005_rename_type_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ManyToManyField(related_name='type', to='auth.Group'),
        ),
    ]
