# Generated by Django 3.2.8 on 2023-09-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_auto_20230905_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
