# Generated by Django 3.2.8 on 2023-09-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_user_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='date',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='complaint',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
