# Generated by Django 3.2.8 on 2023-09-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_remove_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(to='complaints.Department'),
        ),
        migrations.DeleteModel(
            name='EmployeeToDepartment',
        ),
    ]
