# Generated by Django 3.2.8 on 2023-09-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_auto_20230906_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='departments',
        ),
    ]
