# Generated by Django 3.2.8 on 2023-09-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_auto_20230917_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
