# Generated by Django 3.2.8 on 2023-09-19 13:33

import complaints.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_remove_user_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='remark',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='remark',
            name='remark_targeted_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaints.department'),
        ),
        migrations.AddField(
            model_name='remark',
            name='remark_targeted_personnel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='remark_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remark',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarker', to='complaints.complaint'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, validators=[complaints.models.User.validate_districts]),
        ),
    ]
