# Generated by Django 3.2.8 on 2023-09-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_auto_20230919_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='attachment_type',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='attachment_type',
        ),
    ]
