# Generated by Django 3.2.8 on 2023-09-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_auto_20230919_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='targeted_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_department', to='complaints.department'),
        ),
        migrations.CreateModel(
            name='DepartmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Opened', 'Opened'), ('Forwarded', 'Forwarded'), ('Closed', 'Closed')], default='Opened', max_length=20)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.department')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='department_history',
            field=models.ManyToManyField(blank=True, related_name='history', through='complaints.DepartmentHistory', to='complaints.Department'),
        ),
    ]
