# Generated by Django 3.2.8 on 2023-09-22 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_auto_20230920_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-date_added']},
        ),
    ]
